export default {
    SET_DANCE_VIDEOS: "SET_DANCE_VIDEOS",
    SET_SHOW_PLAYLISTS: "SET_SHOW_PLAYLISTS",
    SET_MUSIC_VIDEOS: "SET_MUSIC_VIDEOS",
    SET_EDUCATIONAL_VIDEOS: "SET_EDUCATIONAL_VIDEOS"
};